# --------------------------------------------------------
# Octree-based Sparse Convolutional Neural Networks
# Copyright (c) 2022 Peng-Shuai Wang <wangps@hotmail.com>
# Licensed under The MIT License [see LICENSE for details]
# Written by Peng-Shuai Wang
# --------------------------------------------------------

SOLVER:
  gpu: 0,
  run: train

  logdir: logs/completion/gso
  max_epoch: 300
  test_every_epoch: 1
  log_per_iter: 50
  ckpt_num: 20

  # optimizer
  type: adamw
  weight_decay: 0.01  # default value of adamw
  lr: 0.001           # default value of adamw

  # learning rate
  lr_type: poly
  milestones: (160,240)

DATA:
  train:
    name: completion
    points_scale: 128

    # octree building
    depth: 6
    full_depth: 2

    # no data augmentations
    distort: False

    # data loading, reuse the data for autoencoder
    location: /data/hewenhao/code/learn_to_pick/tools/ocnn/train/*/  # data/ocnn_completion/shape.ply
    filelist: data/ocnn_completion/filelist_train.txt
    batch_size: 32
    shuffle: True
    # num_workers: 0

  test:
    name: completion

    # octree building
    depth: 6
    full_depth: 2

    # no data augmentations
    distort: False

    # data loading
    location: /data/hewenhao/code/learn_to_pick/tools/ocnn/2024-08-22_15-59-54  # data/ocnn_completion/shape.ply
    filelist: data/ocnn_completion/filelist_test.txt
    batch_size: 16
    shuffle: False
    # num_workers: 0

MODEL:
  name: ounet
  feature: L   # L -> Local coordinates (3 channel)
  channel: 3
  nout: 4
  depth: 6
  full_depth: 2
